/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as auctionSol from "./auction.sol";
export type { auctionSol };
import type * as auctionfactorySol from "./auctionfactory.sol";
export type { auctionfactorySol };
import type * as genCreditSol from "./genCredit.sol";
export type { genCreditSol };
import type * as imagenftSol from "./imagenft.sol";
export type { imagenftSol };
import type * as promptnftSol from "./promptnft.sol";
export type { promptnftSol };
