/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace CreditManagement {
  export type UpdateCreditsRequestStruct = {
    user: AddressLike;
    nonce: BigNumberish;
  };

  export type UpdateCreditsRequestStructOutput = [
    user: string,
    nonce: bigint
  ] & { user: string; nonce: bigint };
}

export interface CreditManagementInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "canUpdateCredit"
      | "creditsPerPayment"
      | "dailyCreditLimit"
      | "getCredits"
      | "lastCreditUpdate"
      | "monthlyCreditLimit"
      | "nonceUsed"
      | "owner"
      | "purchaseCredits"
      | "updateCredits"
      | "updateCreditsMeta"
      | "useCredits"
      | "userCredits"
      | "withdrawEther"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CreditsPurchased" | "CreditsUsed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "canUpdateCredit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "creditsPerPayment",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dailyCreditLimit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCredits",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastCreditUpdate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "monthlyCreditLimit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nonceUsed",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "purchaseCredits",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateCredits",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateCreditsMeta",
    values: [CreditManagement.UpdateCreditsRequestStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "useCredits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userCredits",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawEther",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "canUpdateCredit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creditsPerPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dailyCreditLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getCredits", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastCreditUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "monthlyCreditLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nonceUsed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "purchaseCredits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCredits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCreditsMeta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "useCredits", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userCredits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawEther",
    data: BytesLike
  ): Result;
}

export namespace CreditsPurchasedEvent {
  export type InputTuple = [user: AddressLike, creditsPurchased: BigNumberish];
  export type OutputTuple = [user: string, creditsPurchased: bigint];
  export interface OutputObject {
    user: string;
    creditsPurchased: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreditsUsedEvent {
  export type InputTuple = [user: AddressLike, creditsUsed: BigNumberish];
  export type OutputTuple = [user: string, creditsUsed: bigint];
  export interface OutputObject {
    user: string;
    creditsUsed: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CreditManagement extends BaseContract {
  connect(runner?: ContractRunner | null): CreditManagement;
  waitForDeployment(): Promise<this>;

  interface: CreditManagementInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  canUpdateCredit: TypedContractMethod<[], [boolean], "view">;

  creditsPerPayment: TypedContractMethod<[], [bigint], "view">;

  dailyCreditLimit: TypedContractMethod<[], [bigint], "view">;

  getCredits: TypedContractMethod<[], [bigint], "view">;

  lastCreditUpdate: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  monthlyCreditLimit: TypedContractMethod<[], [bigint], "view">;

  nonceUsed: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  purchaseCredits: TypedContractMethod<[], [void], "payable">;

  updateCredits: TypedContractMethod<[], [void], "nonpayable">;

  updateCreditsMeta: TypedContractMethod<
    [
      request: CreditManagement.UpdateCreditsRequestStruct,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  useCredits: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  userCredits: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  withdrawEther: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "canUpdateCredit"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "creditsPerPayment"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "dailyCreditLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCredits"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastCreditUpdate"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "monthlyCreditLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nonceUsed"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "purchaseCredits"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "updateCredits"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateCreditsMeta"
  ): TypedContractMethod<
    [
      request: CreditManagement.UpdateCreditsRequestStruct,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "useCredits"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userCredits"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawEther"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "CreditsPurchased"
  ): TypedContractEvent<
    CreditsPurchasedEvent.InputTuple,
    CreditsPurchasedEvent.OutputTuple,
    CreditsPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "CreditsUsed"
  ): TypedContractEvent<
    CreditsUsedEvent.InputTuple,
    CreditsUsedEvent.OutputTuple,
    CreditsUsedEvent.OutputObject
  >;

  filters: {
    "CreditsPurchased(address,uint256)": TypedContractEvent<
      CreditsPurchasedEvent.InputTuple,
      CreditsPurchasedEvent.OutputTuple,
      CreditsPurchasedEvent.OutputObject
    >;
    CreditsPurchased: TypedContractEvent<
      CreditsPurchasedEvent.InputTuple,
      CreditsPurchasedEvent.OutputTuple,
      CreditsPurchasedEvent.OutputObject
    >;

    "CreditsUsed(address,uint256)": TypedContractEvent<
      CreditsUsedEvent.InputTuple,
      CreditsUsedEvent.OutputTuple,
      CreditsUsedEvent.OutputObject
    >;
    CreditsUsed: TypedContractEvent<
      CreditsUsedEvent.InputTuple,
      CreditsUsedEvent.OutputTuple,
      CreditsUsedEvent.OutputObject
    >;
  };
}
