/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as auctionSol from "./auction.sol";
export * as auctionfactorySol from "./auctionfactory.sol";
export * as genCreditSol from "./genCredit.sol";
export * as imagenftSol from "./imagenft.sol";
export * as promptnftSol from "./promptnft.sol";
